version: '3.3'

services:
  frontend:
    image: node:21
    working_dir: /app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm install && npm run build --prod && exec nginx -g 'daemon off;'"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - frontend
